version: '3.8'

services:
  api:
    build: ./api
    ports:
      - "3000:3000"
    volumes:
      - ./api:/usr/src/app
      - /usr/src/app/node_modules
    
    environment:
      - NODE_ENV=development
    env_file:
      - ./api/.env
  web:
    build: ./web
    ports:
      - "5173:5173"
    volumes:
      - ./web:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development